// Code generated by cmd/gen-eventschema; DO NOT EDIT.
// Source of truth: schema/events.json. Run `just gen` to regenerate.

package session

// EventType consts. EventType itself is declared in event.go.
const (
	EventSessionStarted       EventType = "session.started"
	EventSessionStatusChanged EventType = "session.status_changed"
	EventSessionTerminating   EventType = "session.terminating"
	EventTurnStarted          EventType = "turn.started"
	EventTurnCompleted        EventType = "turn.completed"
	EventTurnFailed           EventType = "turn.failed"
	EventTurnInterrupted      EventType = "turn.interrupted"
	EventMessageStarted       EventType = "message.started"
	EventMessageDelta         EventType = "message.delta"
	EventMessageCompleted     EventType = "message.completed"
	EventReasoningStarted     EventType = "reasoning.started"
	EventReasoningDelta       EventType = "reasoning.delta"
	EventReasoningCompleted   EventType = "reasoning.completed"
	EventToolStarted          EventType = "tool.started"
	EventToolDelta            EventType = "tool.delta"
	EventToolCompleted        EventType = "tool.completed"
	EventToolFailed           EventType = "tool.failed"
	EventPermissionRequested  EventType = "permission.requested"
	EventPermissionResolved   EventType = "permission.resolved"
	EventTodoUpdated          EventType = "todo.updated"
	EventUsageUpdated         EventType = "usage.updated"
	EventRateLimitUpdated     EventType = "rate_limit.updated"
	EventWorkspaceStatus      EventType = "workspace.status"
	EventSessionTitle         EventType = "session.title"
	EventModelsAvailable      EventType = "models.available"
	EventError                EventType = "error"
)

// AllEventTypes is every event type, in schema order. The drift test in
// schema_test.go asserts this matches schema/events.json exactly.
var AllEventTypes = []EventType{
	EventSessionStarted,
	EventSessionStatusChanged,
	EventSessionTerminating,
	EventTurnStarted,
	EventTurnCompleted,
	EventTurnFailed,
	EventTurnInterrupted,
	EventMessageStarted,
	EventMessageDelta,
	EventMessageCompleted,
	EventReasoningStarted,
	EventReasoningDelta,
	EventReasoningCompleted,
	EventToolStarted,
	EventToolDelta,
	EventToolCompleted,
	EventToolFailed,
	EventPermissionRequested,
	EventPermissionResolved,
	EventTodoUpdated,
	EventUsageUpdated,
	EventRateLimitUpdated,
	EventWorkspaceStatus,
	EventSessionTitle,
	EventModelsAvailable,
	EventError,
}
