// Code generated by cmd/gen-eventschema; DO NOT EDIT.
// Source of truth: schema/events.json. Run `just gen` to regenerate.

/**
 * The CLI<->runner wire protocol version. Bump schema/events.json's
 * protocolVersion whenever a change to the event model, HTTP contract, or
 * SSE framing could silently misbehave against an older/newer counterpart.
 * Served on GET /healthz (and /sessions/:id/status) so the CLI can detect
 * skew — see internal/runner.Client.Health and its callers (they warn, not
 * refuse, since OSS users routinely pair a self-built runner against a
 * different CLI version).
 */
export const PROTOCOL_VERSION = 2;

/** Canonical event type enum. */
export type EventType =
  | 'session.started'
  | 'session.status_changed'
  | 'session.terminating'
  | 'turn.started'
  | 'turn.completed'
  | 'turn.failed'
  | 'turn.interrupted'
  | 'message.started'
  | 'message.delta'
  | 'message.completed'
  | 'reasoning.started'
  | 'reasoning.delta'
  | 'reasoning.completed'
  | 'tool.started'
  | 'tool.delta'
  | 'tool.completed'
  | 'tool.failed'
  | 'permission.requested'
  | 'permission.resolved'
  | 'todo.updated'
  | 'usage.updated'
  | 'context.compacted'
  | 'rate_limit.updated'
  | 'workspace.status'
  | 'session.title'
  | 'models.available'
  | 'autopilot.state'
  | 'error';

/** Every event type, in schema order. */
export const ALL_EVENT_TYPES: EventType[] = [
  'session.started',
  'session.status_changed',
  'session.terminating',
  'turn.started',
  'turn.completed',
  'turn.failed',
  'turn.interrupted',
  'message.started',
  'message.delta',
  'message.completed',
  'reasoning.started',
  'reasoning.delta',
  'reasoning.completed',
  'tool.started',
  'tool.delta',
  'tool.completed',
  'tool.failed',
  'permission.requested',
  'permission.resolved',
  'todo.updated',
  'usage.updated',
  'context.compacted',
  'rate_limit.updated',
  'workspace.status',
  'session.title',
  'models.available',
  'autopilot.state',
  'error',
];

/** a single entry in a todo.updated list, mirroring the SDK TodoWrite tool's items. */
export interface TodoItem {
  /** imperative description of the task */
  content: string;
  /** pending | in_progress | completed */
  status: string;
  /** present-tense form shown while in_progress */
  activeForm?: string;
}

/** one model from the SDK's supportedModels() list (models.available), used to populate the in-session /model palette dynamically instead of the hardcoded opus/sonnet/haiku aliases. */
export interface ModelInfo {
  /** model id to use in API calls / --model (e.g. claude-opus-4-8) */
  value: string;
  /** human-readable name (e.g. 'Opus 4.8') */
  displayName: string;
  /** short capability description; may be empty */
  description?: string;
}

/** payload for session.started events: the model, pod cwd, tools, and applied permission mode reported by the SDK init message. The CLI uses model+cwd for the status line and the model id to look up the context-window limit (ctx%). */
export interface SessionStartedPayload {
  model: string;
  cwd: string;
  tools?: string[];
  permissionMode?: string;
  agentSessionId?: string;
}

/** payload for session.status_changed events. */
export interface SessionStatusPayload {
  /** idle | busy | error */
  status: string;
  /** why the status changed (e.g. SessionEnd reason) */
  reason?: string;
}

/** payload for session.terminating events (SIGTERM: drain/suspend/eviction). */
export interface TerminatingPayload {
  /** human-readable cause, e.g. "pod terminating (SIGTERM)" */
  reason: string;
  /** best-effort seconds before SIGKILL */
  graceSeconds: number;
  /** in-flight turns aborted during shutdown */
  turnsAborted: number;
}

/** payload for turn.started events: the prompt that drives this turn. `prompt` is the user's (or autopilot's /loop) message; it is absent when the runner only mirrors an externally-driven turn (the opencode observer emits turn.started with no prompt because the attached opencode client owns the input). Clients render the prompt as a user block so a replayed/attached transcript shows the question, not just the answer. */
export interface TurnStartedPayload {
  /** the user/autopilot prompt that started this turn; absent for observer-mirrored turns */
  prompt?: string;
}

/** payload for turn.completed events: the terminal result summary. Every field is optional — the Claude backend fills them from the SDK result message; the opencode backend emits turn.completed with an empty payload (its result text arrives via message.completed instead). */
export interface TurnCompletedPayload {
  /** final assistant result text (Claude SDK result.result); absent on opencode */
  result?: string;
  /** SDK stop reason (e.g. "end_turn"); absent on opencode */
  stopReason?: string;
  /** SDK-internal sub-turn count for this turn; absent on opencode */
  numTurns?: number;
  /** wall-clock duration of the turn in milliseconds; absent on opencode */
  durationMs?: number;
}

/** payload for turn.failed events: a turn that ended in error. `message` is always present (a human-readable reason; the runner also emits a parallel `error` event with the same text). `subtype` and `errors` are the richer Claude result-path detail (the SDK result subtype + the individual error strings) and are absent on the opencode backend and the Claude mid-turn failure path, which emit `message` only. The Go TUI renders `message`. */
export interface TurnFailedPayload {
  /** human-readable failure reason */
  message: string;
  /** SDK result subtype for the failure (Claude result path only) */
  subtype?: string;
  /** individual SDK error strings (Claude result path only) */
  errors?: string[];
}

/** payload for turn.interrupted events: an in-flight turn torn down before it completed. `reason` names the cause (e.g. "client interrupt", "runner restart", "opencode observer stream ended"). Emitted by the server on an explicit interrupt, on boot recovery for an orphaned turn (D2), and by the opencode observer when its stream ends mid-turn. */
export interface TurnInterruptedPayload {
  /** human-readable cause of the interrupt */
  reason: string;
}

/** payload for message.* events (reasoning.* events reuse this shape, carrying content only). parentToolUseId marks a subagent's stream: when set, the chunk belongs to the Task tool_use id named there, and clients must route it to that subagent's presentation — never into the main streaming transcript, where it would interleave with (and corrupt) the main reply (§2b gap 1). */
export interface MessagePayload {
  /** user | assistant */
  role: string;
  /** text content or delta */
  content: string;
  /** true for message.delta events */
  delta?: boolean;
  /** Task tool_use id that spawned the emitting subagent (empty on the main thread) */
  parentToolUseId?: string;
}

/** payload for tool.* events. */
export interface ToolPayload {
  /** "Bash", "Edit", etc. */
  tool: string;
  /** tool input */
  input?: unknown;
  /** tool output (completed) */
  output?: string;
  /** tool.delta: a chunk of the tool's input JSON as it streams (input_json_delta) */
  partialJson?: string;
  /** Bash exit code */
  exitCode?: number;
  error?: string;
  /** this tool_use block's id */
  toolUseId?: string;
  /** Task tool_use id that spawned a subagent's child tool (empty on main thread) */
  parentToolUseId?: string;
  /** subagent_type for a Task tool (the dispatched agent name) */
  agentName?: string;
}

/** payload for permission.* events. */
export interface PermissionPayload {
  permissionId: string;
  tool: string;
  input: unknown;
  /** "allow-once" | "allow-session" | "deny" | "" (pending) */
  decision?: string;
}

/** payload for usage.updated events. */
export interface UsagePayload {
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
  totalCostUsd: number;
}

/** payload for rate_limit.updated events: the claude.ai plan usage windows (5-hour + weekly, plus the optional per-model weekly Opus/Sonnet caps) and their reset instants, fetched from the SDK's structured /usage data (Query.usage_EXPERIMENTAL...). `available` is false for API-key/Bedrock/Vertex sessions where plan limits do not apply; the TUI hides the windows then rather than fabricating values. Utilizations are 0-100; resets are ISO 8601 (RFC3339) and may be empty when the SDK reports null. The per-model windows are absent (nil pointer / undefined) unless the plan has a separate cap for that model; the status line surfaces the one matching the attached model. The runner emits this during a turn (the control channel is only open until the result closes stdin), so the status line shows real reset times instead of projecting 5h/7d from the wall clock. */
export interface RateLimitPayload {
  /** rate_limits_available: true only for claude.ai subscription sessions */
  available: boolean;
  /** claude.ai subscription type ('pro'/'max'/'team'/'enterprise'), or empty/absent for headless setup-token, API-key, or 3rd-party-provider sessions where plan limits do not apply. When `available` is false and this is empty, the TUI renders 'usage n/a (headless auth)' so the absent windows read as an auth-mode limitation rather than a bug. */
  subscriptionType?: string;
  /** 5-hour window utilization, 0-100 */
  fiveHourUtil: number;
  /** ISO 8601 instant the 5-hour window resets; empty if unknown */
  fiveHourResetsAt?: string;
  /** weekly (7-day) window utilization, 0-100 */
  sevenDayUtil: number;
  /** ISO 8601 instant the weekly window resets; empty if unknown */
  sevenDayResetsAt?: string;
  /** per-model weekly (7-day) Opus window utilization, 0-100; nil/absent when the plan has no separate Opus weekly cap (a non-nil pointer to 0 means present at 0%) */
  sevenDayOpusUtil?: number;
  /** ISO 8601 instant the weekly Opus window resets; empty if unknown */
  sevenDayOpusResetsAt?: string;
  /** per-model weekly (7-day) Sonnet window utilization, 0-100; nil/absent when the plan has no separate Sonnet weekly cap (a non-nil pointer to 0 means present at 0%) */
  sevenDaySonnetUtil?: number;
  /** ISO 8601 instant the weekly Sonnet window resets; empty if unknown */
  sevenDaySonnetResetsAt?: string;
}

/** payload for workspace.status events: git branch + dirty/ahead/behind for the status line. Emitted at session start and after each turn; skipped for non-git cwd. */
export interface WorkspaceStatusPayload {
  branch: string;
  dirty: boolean;
  ahead: number;
  behind: number;
}

/** payload for session.title events: a short conversation-derived summary emitted once per session after the first assistant turn. */
export interface SessionTitlePayload {
  title: string;
}

/** payload for models.available events: the list of models the account/SDK supports (Query.supportedModels()), used to populate the in-session /model palette dynamically. Emitted once per session, fetched in-turn on the SDK init message (same open-control-channel window as rate_limit.updated). Absent until the first turn runs; the TUI falls back to the opus/sonnet/haiku aliases until it arrives. */
export interface ModelsAvailablePayload {
  /** the supported models, in SDK order */
  models: ModelInfo[];
}

/** payload for todo.updated events: the agent's current task list, emitted by the runner whenever the SDK TodoWrite tool runs. The TUI renders it as a checklist. */
export interface TodoUpdatedPayload {
  /** the full todo list (replaces any prior list) */
  todos: TodoItem[];
}

/** payload for error events. */
export interface ErrorPayload {
  message: string;
  code?: string;
}

/** payload for context.compacted events: emitted when the SDK compacts (summarizes) the conversation to fit the context window. preTokens/postTokens let the TUI reset the ctx% gauge to the post-compaction size instead of the stale pre-compaction count, and drop a one-line transcript marker. */
export interface ContextCompactedPayload {
  /** 'auto' (context-window pressure) or 'manual' (/compact) */
  trigger: string;
  /** effective token count before compaction */
  preTokens: number;
  /** effective token count after compaction; 0/absent when the SDK did not report it */
  postTokens?: number;
}

/** payload for autopilot.state events: a transition of the runner-owned autopilot driver (the server-side /loop-/goal loop; see docs/archive/server-side-loop-adr.md). Emitted on arm (state:'armed' — re-emitted on a boot re-arm so a fresh `sandbox attach` re-renders the armed chip without special-casing), at each iteration boundary (state:'ticked', carrying the iteration count for the TUI's progress chip), and on termination (state:'stopped' with a reason). The TUI renders the driver PURELY from these events (armed chip, iteration counter, terminal toast/OS-notification), so a replayed stopped(sentinel) must not re-fire the OS notification — only the flip-to-live one does. */
export interface AutopilotStatePayload {
  /** 'armed' | 'ticked' | 'stopped' */
  state: string;
  /** 'loop' | 'goal' — the driver flavour */
  kind: string;
  /** set on state:'stopped' — 'sentinel' | 'budget' | 'user' | 'lapsed' | 'error' (mirrors the spec's stopped_reason); absent otherwise */
  reason?: string;
  /** completed-iteration count at this transition (0 on the initial armed event) */
  iteration: number;
  /** the driver generation; a disarm/rearm bumps it so a stale scheduled tick fired against an old gen is dropped */
  gen: number;
}
