// Code generated by cmd/gen-eventschema; DO NOT EDIT.
// Source of truth: schema/events.json. Run `just gen` to regenerate.

/**
 * The CLI<->runner wire protocol version. Bump schema/events.json's
 * protocolVersion whenever a change to the event model, HTTP contract, or
 * SSE framing could silently misbehave against an older/newer counterpart.
 * Served on GET /healthz (and /sessions/:id/status) so the CLI can detect
 * skew — see internal/runner.Client.Health and its callers (they warn, not
 * refuse, since OSS users routinely pair a self-built runner against a
 * different CLI version).
 */
export const PROTOCOL_VERSION = 3;

/** Canonical event type enum. */
export type EventType =
  | 'session.started'
  | 'session.status_changed'
  | 'session.terminating'
  | 'turn.started'
  | 'turn.completed'
  | 'turn.failed'
  | 'turn.interrupted'
  | 'message.started'
  | 'message.delta'
  | 'message.completed'
  | 'reasoning.started'
  | 'reasoning.delta'
  | 'reasoning.completed'
  | 'tool.started'
  | 'tool.completed'
  | 'tool.failed'
  | 'permission.requested'
  | 'permission.resolved'
  | 'usage.updated'
  | 'context.compacted'
  | 'rate_limit.updated'
  | 'workspace.status'
  | 'session.title'
  | 'error';

/** Every event type, in schema order. */
export const ALL_EVENT_TYPES: EventType[] = [
  'session.started',
  'session.status_changed',
  'session.terminating',
  'turn.started',
  'turn.completed',
  'turn.failed',
  'turn.interrupted',
  'message.started',
  'message.delta',
  'message.completed',
  'reasoning.started',
  'reasoning.delta',
  'reasoning.completed',
  'tool.started',
  'tool.completed',
  'tool.failed',
  'permission.requested',
  'permission.resolved',
  'usage.updated',
  'context.compacted',
  'rate_limit.updated',
  'workspace.status',
  'session.title',
  'error',
];

/** one source citation attached to an assistant message (message.completed only, §2b gap 6). Flattened from the SDK's five citation location shapes to what a footnote render needs: web citations carry url+title, document/search citations carry title (document_title or source) only. citedText is the quoted snippet, capped by the mapper. */
export interface Citation {
  /** source URL (web_search_result_location citations) */
  url?: string;
  /** source title (or document title / search-result source for non-web citations) */
  title?: string;
  /** the cited snippet, mapper-capped at 200 chars */
  citedText?: string;
}

/** payload for session.started events: the model (and, when known, cwd + backend resume id) reported by a backend observer. The opencode and claude-pane observers re-emit it on every model CHANGE (deduped) so the Go read-model resolves a context-window limit for the ctx% indicator and the dashboard chip; cwd may be empty for observer-mirrored sessions. */
export interface SessionStartedPayload {
  model: string;
  cwd: string;
  agentSessionId?: string;
}

/** payload for session.status_changed events. */
export interface SessionStatusPayload {
  /** idle | busy | error */
  status: string;
  /** why the status changed (e.g. SessionEnd reason) */
  reason?: string;
}

/** payload for session.terminating events (SIGTERM: drain/suspend/eviction). */
export interface TerminatingPayload {
  /** human-readable cause, e.g. "pod terminating (SIGTERM)" */
  reason: string;
  /** best-effort seconds before SIGKILL */
  graceSeconds: number;
  /** in-flight turns aborted during shutdown */
  turnsAborted: number;
}

/** payload for turn.started events: the prompt that drives this turn. `prompt` is the user's message when the runner knows it (the claude-pane observer's UserPromptSubmit hook, the opencode headless first turn); it is absent when the runner only mirrors an externally-driven turn whose input the attached client owns. Clients render the prompt as a user block so a replayed/attached transcript shows the question, not just the answer. */
export interface TurnStartedPayload {
  /** the user prompt that started this turn; absent for observer-mirrored turns without one */
  prompt?: string;
}

/** payload for turn.completed events: the terminal result summary. `result` is the complete final assistant message when the backend reports one (the claude-pane observer's Stop hook); the opencode and codex observers emit turn.completed with an empty payload (their result text arrives via message.completed instead). */
export interface TurnCompletedPayload {
  /** final assistant result text; absent when the backend does not report it */
  result?: string;
}

/** payload for turn.failed events: a turn that ended in error. `message` is always present (a human-readable reason; the runner also emits a parallel `error` event with the same text). `subtype` and `errors` are the richer Claude result-path detail (the SDK result subtype + the individual error strings) and are absent on the opencode backend and the Claude mid-turn failure path, which emit `message` only. The Go TUI renders `message`. */
export interface TurnFailedPayload {
  /** human-readable failure reason */
  message: string;
  /** SDK result subtype for the failure (Claude result path only) */
  subtype?: string;
  /** individual SDK error strings (Claude result path only) */
  errors?: string[];
}

/** payload for turn.interrupted events: an in-flight turn torn down before it completed. `reason` names the cause (e.g. "client interrupt", "runner restart", "opencode observer stream ended"). Emitted by the server on an explicit interrupt, on boot recovery for an orphaned turn (D2), and by the opencode observer when its stream ends mid-turn. */
export interface TurnInterruptedPayload {
  /** human-readable cause of the interrupt */
  reason: string;
}

/** payload for message.* events (reasoning.* events reuse this shape, carrying content only). parentToolUseId marks a subagent's stream: when set, the chunk belongs to the Task tool_use id named there, and clients must route it to that subagent's presentation — never into the main streaming transcript, where it would interleave with (and corrupt) the main reply (§2b gap 1). */
export interface MessagePayload {
  /** user | assistant */
  role: string;
  /** text content or delta */
  content: string;
  /** true for message.delta events */
  delta?: boolean;
  /** Task tool_use id that spawned the emitting subagent (empty on the main thread) */
  parentToolUseId?: string;
  /** sources cited by this text (message.completed only; never on started/delta). Clients render as a footnote list. No backend currently emits citations (claude SDK engine removed); retained with its consumer for observer revival. */
  citations?: Citation[];
}

/** payload for tool.* events. */
export interface ToolPayload {
  /** "Bash", "Edit", etc. */
  tool: string;
  /** tool input */
  input?: unknown;
  /** tool output (completed) */
  output?: string;
  /** Bash exit code */
  exitCode?: number;
  error?: string;
  /** this tool_use block's id */
  toolUseId?: string;
  /** Task tool_use id that spawned a subagent's child tool (empty on main thread) */
  parentToolUseId?: string;
  /** subagent_type for a Task tool (the dispatched agent name) */
  agentName?: string;
}

/** payload for permission.* events. */
export interface PermissionPayload {
  permissionId: string;
  tool: string;
  input: unknown;
  /** "allow-once" | "allow-session" | "deny" | "" (pending) */
  decision?: string;
}

/** payload for usage.updated events. */
export interface UsagePayload {
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
  totalCostUsd: number;
}

/** payload for rate_limit.updated events: the claude.ai plan usage windows (5-hour + weekly, plus the optional per-model weekly Opus/Sonnet caps) and their reset instants, fetched from the SDK's structured /usage data (Query.usage_EXPERIMENTAL...). `available` is false for API-key/Bedrock/Vertex sessions where plan limits do not apply; the TUI hides the windows then rather than fabricating values. Utilizations are 0-100; resets are ISO 8601 (RFC3339) and may be empty when the SDK reports null. The per-model windows are absent (nil pointer / undefined) unless the plan has a separate cap for that model; the status line surfaces the one matching the attached model. The runner emits this during a turn (the control channel is only open until the result closes stdin), so the status line shows real reset times instead of projecting 5h/7d from the wall clock. */
export interface RateLimitPayload {
  /** rate_limits_available: true only for claude.ai subscription sessions */
  available: boolean;
  /** claude.ai subscription type ('pro'/'max'/'team'/'enterprise'), or empty/absent for headless setup-token, API-key, or 3rd-party-provider sessions where plan limits do not apply. When `available` is false and this is empty, the TUI renders 'usage n/a (headless auth)' so the absent windows read as an auth-mode limitation rather than a bug. */
  subscriptionType?: string;
  /** 5-hour window utilization, 0-100 */
  fiveHourUtil: number;
  /** ISO 8601 instant the 5-hour window resets; empty if unknown */
  fiveHourResetsAt?: string;
  /** weekly (7-day) window utilization, 0-100 */
  sevenDayUtil: number;
  /** ISO 8601 instant the weekly window resets; empty if unknown */
  sevenDayResetsAt?: string;
  /** per-model weekly (7-day) Opus window utilization, 0-100; nil/absent when the plan has no separate Opus weekly cap (a non-nil pointer to 0 means present at 0%) */
  sevenDayOpusUtil?: number;
  /** ISO 8601 instant the weekly Opus window resets; empty if unknown */
  sevenDayOpusResetsAt?: string;
  /** per-model weekly (7-day) Sonnet window utilization, 0-100; nil/absent when the plan has no separate Sonnet weekly cap (a non-nil pointer to 0 means present at 0%) */
  sevenDaySonnetUtil?: number;
  /** ISO 8601 instant the weekly Sonnet window resets; empty if unknown */
  sevenDaySonnetResetsAt?: string;
}

/** payload for workspace.status events: git branch + dirty/ahead/behind for the session row. NOTE: no backend currently emits this (the claude SDK engine that did was removed by claude-pane-first); the vocabulary + Go consumer (Branch/Dirty read-model) are retained because the pane statusline / backend observers can re-emit it. */
export interface WorkspaceStatusPayload {
  branch: string;
  dirty: boolean;
  ahead: number;
  behind: number;
}

/** payload for session.title events: a short conversation-derived summary emitted once per session after the first assistant turn. */
export interface SessionTitlePayload {
  title: string;
}

/** payload for error events. */
export interface ErrorPayload {
  message: string;
  code?: string;
}

/** payload for context.compacted events: the conversation was compacted (summarized) to fit the context window. preTokens/postTokens let the TUI reset the ctx% gauge to the post-compaction size instead of the stale pre-compaction count. NOTE: no backend currently emits this (the claude SDK engine that did was removed by claude-pane-first); the vocabulary + Go consumer are retained because in-pane compaction is observable and an observer may re-emit it. */
export interface ContextCompactedPayload {
  /** 'auto' (context-window pressure) or 'manual' (/compact) */
  trigger: string;
  /** effective token count before compaction */
  preTokens: number;
  /** effective token count after compaction; 0/absent when not reported */
  postTokens?: number;
}
